# Generated by Django 4.1.13 on 2024-05-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_experience', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrrating',
            name='vr_experience',
        ),
        migrations.AddField(
            model_name='vrexperience',
            name='rating',
            field=models.ManyToManyField(blank=True, to='vr_experience.vrrating'),
        ),
        migrations.AlterField(
            model_name='vrrating',
            name='rating',
            field=models.CharField(blank=True, choices=[('very_satisfied', 'Very Satisfied'), ('satisfied', 'Satisfied'), ('neutral', 'Neutral'), ('dissatisfied', 'Dissatisfied'), ('very_dissatisfied', 'Very Dissatisfied')], max_length=200, null=True),
        ),
    ]
