# Generated by Django 4.1.13 on 2024-05-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrrating',
            name='value',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=200),
        ),
    ]
