# Generated by Django 4.1.13 on 2024-05-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vr_experience', '0002_vrexperience_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrexperience',
            name='duration',
        ),
    ]
