# Generated by Django 4.1.13 on 2024-05-20 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vr_experience', '0004_alter_vrrating_val'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrexperience',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='vrrating',
            name='val',
        ),
        migrations.AddField(
            model_name='vrrating',
            name='value',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', max_length=200),
        ),
        migrations.AddField(
            model_name='vrrating',
            name='vr_experience',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vr_experience.vrexperience'),
        ),
    ]
