# Generated by Django 4.1.13 on 2024-05-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_experience', '0005_remove_vrexperience_rating_remove_vrrating_val_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrexperience',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='vrexperience',
            name='vote_total',
        ),
        migrations.AddField(
            model_name='vrexperience',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
