# Generated by Django 4.1.13 on 2024-05-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('tourist', 'Tourist'), ('tour_agency', 'Tour Agent'), ('hotel', 'Hotel Manager'), ('admin', 'System Administrator')], default='tourist', max_length=200),
        ),
    ]
