# Generated by Django 4.1.13 on 2024-05-31 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='contact_info',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='name',
        ),
    ]
