# Generated by Django 4.1.13 on 2024-05-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
