# Generated by Django 4.1.13 on 2024-05-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/user.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
