# Generated by Django 4.1.13 on 2024-05-20 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_user'),
        ('users', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
    ]
