POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
    "username": "anwar",
    "password": "anwar"
}


###

POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
    "username": "fgrfgr","password":"mike", "email": "mike@anwar.com"
}



###

GET http://127.0.0.1:8000/api/test_token/
Content-Type: application/json
Authorization: Token b183f5f39d3e8074457867745f11cc0896867260

{}

