POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
    "username": "mikhe",
    "password": "mike"
}


###

POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
    "username": "mikhe","password":"mike", "email": "mike@anwar.com"
}



###

GET http://127.0.0.1:8000/api/test_token/
Content-Type: application/json

{}