GET https://server.aiwar365.com/api/login/
Content-Type: application/json

{
    "username": "fgrfgr",
    "password": "mike"
}


###
POST https://server.aiwar365.com/api/login/
Content-Type: application/json

{
    "username": "anwar",
    "password": "anwar"
}
###
POST https://server.aiwar365.com/api/logout/
Content-Type: application/json
Authorization: Token 5fbf8ce061924b2cb33114f9316f909fd8aa562c

{}



###

POST https://server.aiwar365.com/api/register/
Content-Type: application/json

{
    "username": "dda","password":"mike", "email": "mike@anwar.com"
}
###

POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
    "username": "dsda","password":"mike", "email": "mike@anwar.com"
}


###

GET http://127.0.0.1:8000/api/test_token/
Content-Type: application/json
Authorization: Token b183f5f39d3e8074457867745f11cc0896867260

{}


### 

GET  http://127.0.0.1:8000/api/vrs/
Content-Type: application/json
Authorization: Token 018460cb737ccc218de044b835c154d283ca6859

{
    "title": "Lalibela"
}

### 

POST  http://127.0.0.1:8000/api/vrs/
Content-Type: application/json

{
    "title": "Lalibela"
}


###

POST  https://server.aiwar365.com/api/vrs/bookings/
Content-Type: application/json

{
    "user": "3",
    "vr": "2"
}
###

GET  https://server.aiwar365.com/api/mybookings/
Content-Type: application/json

{}
###

PUT  https://server.aiwar365.com/api/users/2/
Content-Type: application/json

{
    "user": {
        "first_name": "Abysinia",
        "last_name": "",
        "password": "mike",
        "email": "abys@dream.com"
    },
    "bio": "",
    "date_of_birth": null,
    "phone_number": null,
    "role": "hotel"
}


### Access protected endpoint

GET https://server.aiwar365.com/api/users/2/
Content-Type: application/json

{}

###

PUT https://server.aiwar365.com/api/users/3/
Content-Type: application/json

{
    "id": 7,
    "user": {
        "id": 7,
        "first_name": "John",
        "last_name": "Doef",
        "email": "john.doe@example.com",
        "username": "johnny", 
        "password": "mike"
    },
    "bio": "Loves hiking and outdoor activities.",
    "date_of_birth": "1990-01-01",
    "phone_number": "123-456-7890",
    "role": "tourist"
}
