# Generated by Django 4.1.13 on 2024-05-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
