# Generated by Django 4.1.13 on 2024-06-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_rename_locations_hotel_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='Hotel',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotels.roomimage'),
        ),
        migrations.AddField(
            model_name='room',
            name='occupancy',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='Single Room', max_length=200),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotels.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
