# Generated by Django 4.1.13 on 2024-06-09 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0004_remove_hotel_rooms_hotel_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='admin',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
