# Generated by Django 4.1.13 on 2024-06-10 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotel_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 8, 5, 34, 294147)),
        ),
    ]
