# Generated by Django 4.1.13 on 2024-06-10 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_roombooking_check_in_roombooking_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 8, 24, 44, 137206)),
        ),
    ]
