# Generated by Django 4.1.13 on 2024-06-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_url',
        ),
        migrations.RemoveField(
            model_name='touragency',
            name='address',
        ),
        migrations.RemoveField(
            model_name='touragency',
            name='tours',
        ),
        migrations.AddField(
            model_name='tour',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='agencies.touragency'),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
