# Generated by Django 4.1.13 on 2024-05-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touragency',
            name='deleted',
        ),
    ]
