# Generated by Django 4.1.13 on 2024-06-10 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agencies', '0002_remove_tour_tags_remove_tour_tour_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touragency',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
